include required(classpath("application"))

docker.hash-lookup.enabled = false

backend {
    default: singularity
    providers: {
        singularity {
            # The backend custom configuration.
            actor-factory = "cromwell.backend.impl.sfs.config.ConfigBackendLifecycleActorFactory"

            config {
                run-in-background = true
                runtime-attributes = """
                  String? docker
                """
                submit-docker = """
			/scratch/gpk00003/20251110full_pipeline/cromwellWithSingularityDockerManip.sh ${docker} ${cwd} ${docker_cwd} ${job_shell} ${docker_script}
                """
            }
        }
    }
}
